INSERT INTO USER (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME) VALUES(TRUE, 'Andrea', 'Mussmann', 'passwd', 'amuss')
INSERT INTO USER_USER_ROLE (USER_USERNAME, ROLES) VALUES ('amuss', 'ADMIN') 
INSERT INTO BOOK(MEDIAID, TITLE, PUBLISHING_DATE, LANGUAGE, TOTAL_AVAIL, CUR_BORROWED, MEDIA_TYPE, AUTHOR, ISBN) VALUES (1, '20.000 Meilen unter dem Meer', '2017-01-01', 'GE', 4, 0, 'BOOK', 'Jules Vernes', '978-395-728045-9')
INSERT INTO AUDIO_BOOK (MEDIAID, TITLE, PUBLISHING_DATE, LANGUAGE, TOTAL_AVAIL, CUR_BORROWED, MEDIA_TYPE, AUTHOR, ISBN, LENGTH, SPEAKER) VALUES (2, '20.000 Meilen unter dem Meer', '2009-08-11', 'GE', 20, 0, 'AUDIOBOOK', 'Jules Vernes', '978-3-89813-905-2', 2640, 'Peter G. Hubler')
INSERT INTO MAGAZINE(MEDIAID, TITLE, PUBLISHING_DATE, LANGUAGE, TOTAL_AVAIL, CUR_BORROWED, MEDIA_TYPE, SERIES) VALUES (3, 'Playboy', '2009-11-01', 'GE', 14, 0, 'MAGAZINE', 'Monthly Playboy')
INSERT INTO VIDEO(MEDIAID, TITLE, PUBLISHING_DATE, LANGUAGE, TOTAL_AVAIL, CUR_BORROWED, MEDIA_TYPE, LENGTH) VALUES (4, 'The Silicon Valley Stroy', '1999-05-02', 'EN', 6, 0, 'VIDEO', 5580)

